### PR TITLE
minimal changes to make nwat =4 compatible with Ferrier-Aligo MP scheme

### PR DESCRIPTION
**Pull request by mzhangw**
This PR includes minimal changes  in order to make nwat =4 compatible with Ferrier-Aligo MP scheme following guidance of Rusty Benson and Lucas Harris at GFDL.

### CODE REVIEW

**Comment by climbfuji** [comment]
I cannot judge the scientific correctness. But I guess my question is if there is functionality that we are breaking, i.e. is there another nwat=4 testcase that needs to run in CCPP with the old logic? Otherwise this looks good to me.

**Comment by mzhangw** [comment]
The origin NWAT =4 is tied with Kessler warm rain scheme, which is not in
CCPP-Physics yet. For now, only FA MP uses nwat = 4

**Comment by climbfuji** [comment]
Great, thanks for the clarification.

**Comment by climbfuji** [comment]
Please let me know when this and all PRs that are related to it are ready. But I think this one can be merged anytime and doesn't depend on the others being merged.

**Comment by mzhangw** [comment]
all the PRs are ready. Full RTs are passed in this morning. Thanks!

Man

**Comment by climbfuji** [comment]
> all the PRs are ready. Full RTs are passed in this morning. Thanks! Man
> […](#)

Great to hear. Steps to take:
- @mzhangw please link the PRs together (copy & paste the URLs for the different PRs into each of them, see how we usually do it (Associated PRs: ...)
- @mzhangw please confirm that (for all repositories) all branches you used to regression-test your changes are up to date with the head of dtc/develop
- @grantfirl please check if all your comments have been addressed and approve if so
- @climbfuji will review the PRs as well
- codeowners (@llpcarson not yet notified) to decide whether we need to clean up the commit history

Thanks!

**Comment by mzhangw** [comment]
associated PRs are listing here:
https://github.com/NCAR/ufs-weather-model/pull/1

All repos is based on the top of dtc/develop last night

most comments are address. Some local constant definition will be addressed
in future PR with Chunxi's improvement.

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
